//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item_Venda
    {
        public int idProduto { get; set; }
        public int idVenda { get; set; }
        public int Quantidade { get; set; }
        public double ValorUnitario { get; set; }
    
        public virtual Produto Produto { get; set; }
        public virtual Venda Venda { get; set; }
    }
}
